name: AxiusMEM
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - rdflib
  - requests
  - certifi
  - charset-normalizer
  - idna
  - urllib3
  - six
  - python-dateutil
  - pytz
  - tzdata
  - isodate
  - pyparsing
  - cffi
  - pycparser
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.57.1
      - anyio==4.9.0
      - cachetools==5.5.2
      - cohere==5.16.1
      - colorama==0.4.6
      - distro==1.9.0
      - eval-type-backport==0.2.2
      - fastavro==1.11.1
      - filelock==3.18.0
      - fsspec==2025.5.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.3
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.33.2
      - jiter==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.26
      - langchain-core==0.3.68
      - langchain-text-splitters==0.3.8
      - langgraph==0.5.2
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.5.2
      - langgraph-sdk==0.1.72
      - langsmith==0.4.4
      - mistralai==1.9.2
      - openai==1.94.0
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - packaging==24.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==1.1.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - tenacity==9.1.2
      - tokenizers==0.21.2
      - tqdm==4.67.1
      - transformers==4.53.1
      - types-requests==2.32.4.20250611
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - xxhash==3.5.0
